name: VueDoc to Aliyun

on:
  push:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 下载代码
    - uses: actions/checkout@v2
    # 安装Nodejs
    - name: Setup Node.js 13.2.0
      uses: actions/setup-node@v1
      with:
        node-version: 13.2.0
    # 安装依赖和编译
    - name: Npm install and build
      # 运行的命令或者 action
      run: |
        yarn
        yarn build
    # 部署到阿里云
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-avzr --delete"
        SOURCE: "src/.vuepress/dist"
        REMOTE_HOST: "47.98.252.43"
        REMOTE_USER: "root"
        TARGET: "/root/vue-docs-next"
